name: try-in-web-ide

on:
  pull_request_target: 
    types: [opened, synchronize]

jobs:
  add-link:
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3
      - name: Eclipse Che Pull Request Link
        id: che-pr-check-gh-action
        uses: dkwon17/try-in-web-ide@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add_comment: true
          add_status: true
          setup_remotes: true
          web_ide_instance: https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com
